// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oneoftest.proto

package oneoftest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OneKind struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneKind) Reset()         { *m = OneKind{} }
func (m *OneKind) String() string { return proto.CompactTextString(m) }
func (*OneKind) ProtoMessage()    {}
func (*OneKind) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ee03393344550e8, []int{0}
}

func (m *OneKind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneKind.Unmarshal(m, b)
}
func (m *OneKind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneKind.Marshal(b, m, deterministic)
}
func (m *OneKind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneKind.Merge(m, src)
}
func (m *OneKind) XXX_Size() int {
	return xxx_messageInfo_OneKind.Size(m)
}
func (m *OneKind) XXX_DiscardUnknown() {
	xxx_messageInfo_OneKind.DiscardUnknown(m)
}

var xxx_messageInfo_OneKind proto.InternalMessageInfo

func (m *OneKind) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AnotherKind struct {
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnotherKind) Reset()         { *m = AnotherKind{} }
func (m *AnotherKind) String() string { return proto.CompactTextString(m) }
func (*AnotherKind) ProtoMessage()    {}
func (*AnotherKind) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ee03393344550e8, []int{1}
}

func (m *AnotherKind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnotherKind.Unmarshal(m, b)
}
func (m *AnotherKind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnotherKind.Marshal(b, m, deterministic)
}
func (m *AnotherKind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnotherKind.Merge(m, src)
}
func (m *AnotherKind) XXX_Size() int {
	return xxx_messageInfo_AnotherKind.Size(m)
}
func (m *AnotherKind) XXX_DiscardUnknown() {
	xxx_messageInfo_AnotherKind.DiscardUnknown(m)
}

var xxx_messageInfo_AnotherKind proto.InternalMessageInfo

func (m *AnotherKind) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type DemoBrokenCbor struct {
	// Types that are valid to be assigned to Payload:
	//	*DemoBrokenCbor_OneKind
	//	*DemoBrokenCbor_AnotherKind
	Payload              isDemoBrokenCbor_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DemoBrokenCbor) Reset()         { *m = DemoBrokenCbor{} }
func (m *DemoBrokenCbor) String() string { return proto.CompactTextString(m) }
func (*DemoBrokenCbor) ProtoMessage()    {}
func (*DemoBrokenCbor) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ee03393344550e8, []int{2}
}

func (m *DemoBrokenCbor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoBrokenCbor.Unmarshal(m, b)
}
func (m *DemoBrokenCbor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoBrokenCbor.Marshal(b, m, deterministic)
}
func (m *DemoBrokenCbor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoBrokenCbor.Merge(m, src)
}
func (m *DemoBrokenCbor) XXX_Size() int {
	return xxx_messageInfo_DemoBrokenCbor.Size(m)
}
func (m *DemoBrokenCbor) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoBrokenCbor.DiscardUnknown(m)
}

var xxx_messageInfo_DemoBrokenCbor proto.InternalMessageInfo

type isDemoBrokenCbor_Payload interface {
	isDemoBrokenCbor_Payload()
}

type DemoBrokenCbor_OneKind struct {
	OneKind *OneKind `protobuf:"bytes,1,opt,name=one_kind,json=oneKind,proto3,oneof"`
}

type DemoBrokenCbor_AnotherKind struct {
	AnotherKind *AnotherKind `protobuf:"bytes,2,opt,name=another_kind,json=anotherKind,proto3,oneof"`
}

func (*DemoBrokenCbor_OneKind) isDemoBrokenCbor_Payload() {}

func (*DemoBrokenCbor_AnotherKind) isDemoBrokenCbor_Payload() {}

func (m *DemoBrokenCbor) GetPayload() isDemoBrokenCbor_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DemoBrokenCbor) GetOneKind() *OneKind {
	if x, ok := m.GetPayload().(*DemoBrokenCbor_OneKind); ok {
		return x.OneKind
	}
	return nil
}

func (m *DemoBrokenCbor) GetAnotherKind() *AnotherKind {
	if x, ok := m.GetPayload().(*DemoBrokenCbor_AnotherKind); ok {
		return x.AnotherKind
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DemoBrokenCbor) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DemoBrokenCbor_OneKind)(nil),
		(*DemoBrokenCbor_AnotherKind)(nil),
	}
}

func init() {
	proto.RegisterType((*OneKind)(nil), "OneKind")
	proto.RegisterType((*AnotherKind)(nil), "AnotherKind")
	proto.RegisterType((*DemoBrokenCbor)(nil), "DemoBrokenCbor")
}

func init() { proto.RegisterFile("oneoftest.proto", fileDescriptor_5ee03393344550e8) }

var fileDescriptor_5ee03393344550e8 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xcf, 0x4b, 0xcd,
	0x4f, 0x2b, 0x49, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe7, 0x62, 0xf7,
	0xcf, 0x4b, 0xf5, 0xce, 0xcc, 0x4b, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0x94, 0xb9, 0xb8, 0x1d, 0xf3, 0xf2, 0x4b,
	0x32, 0x52, 0x8b, 0x50, 0x15, 0x31, 0x21, 0x2b, 0x2a, 0xe5, 0xe2, 0x73, 0x49, 0xcd, 0xcd, 0x77,
	0x2a, 0xca, 0xcf, 0x4e, 0xcd, 0x73, 0x4e, 0xca, 0x2f, 0x12, 0x52, 0xe5, 0xe2, 0xc8, 0xcf, 0x4b,
	0x8d, 0xcf, 0xce, 0xcc, 0x4b, 0x01, 0x9b, 0xc7, 0x6d, 0xc4, 0xa1, 0x07, 0xb5, 0xc8, 0x83, 0x21,
	0x88, 0x3d, 0x1f, 0x6a, 0xa7, 0x21, 0x17, 0x4f, 0x22, 0xc4, 0x74, 0x88, 0x52, 0x26, 0xb0, 0x52,
	0x1e, 0x3d, 0x24, 0x2b, 0x3d, 0x18, 0x82, 0xb8, 0x13, 0x11, 0x5c, 0x27, 0x4e, 0x2e, 0xf6, 0x82,
	0xc4, 0xca, 0x9c, 0xfc, 0xc4, 0x94, 0x24, 0x36, 0xb0, 0x1f, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x71, 0x95, 0x6c, 0x32, 0xd6, 0x00, 0x00, 0x00,
}
